name: Mi primer workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje
        run: echo "Hola, GitHub ActionsÂ estÃ¡Â vivo!Â ðŸš€"
      - name: If develop branch
        if: github.ref == 'refs/heads/develop'
        run: echo "This is the developÂ branch!"
      - name: If main branch
        if: github.ref == 'refs/heads/master'
        run: echo $(pwd)
      